/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EHIDCONTROLLER_AUTODEFS_H
#define S3EHIDCONTROLLER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_HIDCONTROLLER_NAME "s3eHidController"
#define S3E_EXT_HIDCONTROLLER_HASH 0x159afc69

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eHidController", 23)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EHIDCONTROLLER_AUTODEFS_H */
