/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef GAMEPAD_AUTODEFS_H
#define GAMEPAD_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GAMEPAD_NAME "GamePad"
#define S3E_EXT_GAMEPAD_HASH 0xe6a02e94

#endif /* !GAMEPAD_AUTODEFS_H */
