/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eHidController.h"


// Define S3E_EXT_SKIP_LOADER_CALL_LOCK on the user-side to skip LoaderCallStart/LoaderCallDone()-entry.
// e.g. in s3eNUI this is used for generic user-side IwUI-based implementation.
#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
#if defined I3D_ARCH_MIPS || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)) || defined I3D_ARCH_NACLX86_64
// For platforms missing stack-switching (MIPS, WP8, NaCl, etc.) make loader-entry via LoaderCallStart/LoaderCallDone() on the user-side.
#define LOADER_CALL_LOCK
#endif
#endif


#include "s3eHidController_interface.h"

static s3eHidControllerFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x159afc69, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eHidController");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x159afc69, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eHidControllerAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

bool s3eHidControllerIsConnected()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[0] func: s3eHidControllerIsConnected"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerIsConnected);
#endif

    bool ret = g_Ext.m_s3eHidControllerIsConnected();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerIsConnected);
#endif

    return ret;
}

bool s3eHidControllerUpdate()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[1] func: s3eHidControllerUpdate"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerUpdate);
#endif

    bool ret = g_Ext.m_s3eHidControllerUpdate();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerUpdate);
#endif

    return ret;
}

float s3eHidControllerGetStick1XAxis()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[2] func: s3eHidControllerGetStick1XAxis"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetStick1XAxis);
#endif

    float ret = g_Ext.m_s3eHidControllerGetStick1XAxis();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetStick1XAxis);
#endif

    return ret;
}

float s3eHidControllerGetStick1YAxis()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[3] func: s3eHidControllerGetStick1YAxis"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetStick1YAxis);
#endif

    float ret = g_Ext.m_s3eHidControllerGetStick1YAxis();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetStick1YAxis);
#endif

    return ret;
}

float s3eHidControllerGetStick2XAxis()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[4] func: s3eHidControllerGetStick2XAxis"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetStick2XAxis);
#endif

    float ret = g_Ext.m_s3eHidControllerGetStick2XAxis();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetStick2XAxis);
#endif

    return ret;
}

float s3eHidControllerGetStick2YAxis()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[5] func: s3eHidControllerGetStick2YAxis"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetStick2YAxis);
#endif

    float ret = g_Ext.m_s3eHidControllerGetStick2YAxis();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetStick2YAxis);
#endif

    return ret;
}

float s3eHidControllerGetLeftTrigger()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[6] func: s3eHidControllerGetLeftTrigger"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetLeftTrigger);
#endif

    float ret = g_Ext.m_s3eHidControllerGetLeftTrigger();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetLeftTrigger);
#endif

    return ret;
}

float s3eHidControllerGetRightTrigger()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[7] func: s3eHidControllerGetRightTrigger"));

    if (!_extLoad())
        return 0;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetRightTrigger);
#endif

    float ret = g_Ext.m_s3eHidControllerGetRightTrigger();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetRightTrigger);
#endif

    return ret;
}

bool s3eHidControllerGetButtonX()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[8] func: s3eHidControllerGetButtonX"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonX);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonX();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonX);
#endif

    return ret;
}

bool s3eHidControllerGetButtonY()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[9] func: s3eHidControllerGetButtonY"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonY);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonY();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonY);
#endif

    return ret;
}

bool s3eHidControllerGetButtonA()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[10] func: s3eHidControllerGetButtonA"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonA);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonA();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonA);
#endif

    return ret;
}

bool s3eHidControllerGetButtonB()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[11] func: s3eHidControllerGetButtonB"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonB);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonB();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonB);
#endif

    return ret;
}

bool s3eHidControllerGetButtonDPadLeft()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[12] func: s3eHidControllerGetButtonDPadLeft"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonDPadLeft);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonDPadLeft();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonDPadLeft);
#endif

    return ret;
}

bool s3eHidControllerGetButtonDPadRight()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[13] func: s3eHidControllerGetButtonDPadRight"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonDPadRight);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonDPadRight();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonDPadRight);
#endif

    return ret;
}

bool s3eHidControllerGetButtonDPadUp()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[14] func: s3eHidControllerGetButtonDPadUp"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonDPadUp);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonDPadUp();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonDPadUp);
#endif

    return ret;
}

bool s3eHidControllerGetButtonDPadDown()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[15] func: s3eHidControllerGetButtonDPadDown"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonDPadDown);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonDPadDown();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonDPadDown);
#endif

    return ret;
}

bool s3eHidControllerGetButtonLShoulderDown()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[16] func: s3eHidControllerGetButtonLShoulderDown"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonLShoulderDown);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonLShoulderDown();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonLShoulderDown);
#endif

    return ret;
}

bool s3eHidControllerGetButtonRShoulderDown()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[17] func: s3eHidControllerGetButtonRShoulderDown"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonRShoulderDown);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonRShoulderDown();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonRShoulderDown);
#endif

    return ret;
}

bool s3eHidControllerGetButtonStart()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[18] func: s3eHidControllerGetButtonStart"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonStart);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonStart();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonStart);
#endif

    return ret;
}

bool s3eHidControllerGetButtonSelect()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[19] func: s3eHidControllerGetButtonSelect"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonSelect);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonSelect();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonSelect);
#endif

    return ret;
}

bool s3eHidControllerGetButtonStick1()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[20] func: s3eHidControllerGetButtonStick1"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonStick1);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonStick1();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonStick1);
#endif

    return ret;
}

bool s3eHidControllerGetButtonStick2()
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[21] func: s3eHidControllerGetButtonStick2"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonStick2);
#endif

    bool ret = g_Ext.m_s3eHidControllerGetButtonStick2();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerGetButtonStick2);
#endif

    return ret;
}

bool s3eHidControllerUpdateLegacy(float dt)
{
    IwTrace(HIDCONTROLLER_VERBOSE, ("calling s3eHidController[22] func: s3eHidControllerUpdateLegacy"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerUpdateLegacy);
#endif

    bool ret = g_Ext.m_s3eHidControllerUpdateLegacy(dt);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eHidControllerUpdateLegacy);
#endif

    return ret;
}
