
//legacy mapping from rename of GamePad/360Controller to s3eHidController

#include s3eHidController.h

#define GamePad_IsConnected s3eHidControllerIsConnected
#define GamePad_Update s3eHidControllerUpdate
#define GamePad_GetStick1XAxis s3eHidControllerGetStick1XAxis
#define GamePad_GetStick1YAxis s3eHidControllerGetStick1YAxis
#define GamePad_GetStick2XAxis s3eHidControllerGetStick2XAxis
#define GamePad_GetStick2YAxis s3eHidControllerGetStick2YAxis
#define GamePad_GetLeftTrigger s3eHidControllerGetLeftTrigger
#define GamePad_GetRightTrigger s3eHidControllerGetRightTrigger
#define GamePad_GetButtonX s3eHidControllerGetButtonX
#define GamePad_GetButtonY s3eHidControllerGetButtonY
#define GamePad_GetButtonA s3eHidControllerGetButtonA
#define GamePad_GetButtonB s3eHidControllerGetButtonB
#define GamePad_GetButtonDPadLeft s3eHidControllerGetButtonDPadLeft
#define GamePad_GetButtonDPadRight s3eHidControllerGetButtonDPadRight
#define GamePad_GetButtonDPadUp s3eHidControllerGetButtonDPadUp
#define GamePad_GetButtonDPadDown s3eHidControllerGetButtonDPadDown
#define GamePad_GetButtonLShoulderDown s3eHidControllerGetButtonLShoulderDown 
#define GamePad_GetButtonRShoulderDown s3eHidControllerGetButtonRShoulderDown 
#define GamePad_GetButtonStart s3eHidControllerGetButtonStart
#define GamePad_GetButtonSelect s3eHidControllerGetButtonSelect
