/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_HIDCONTROLLER_H
#define S3E_EXT_HIDCONTROLLER_H

#include <s3eTypes.h>
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the HidController extension is available.
 */
s3eBool s3eHidControllerAvailable();

bool s3eHidControllerIsConnected();

bool s3eHidControllerUpdate(float dt);

float s3eHidControllerGetStick1XAxis();

float s3eHidControllerGetStick1YAxis();

float s3eHidControllerGetStick2XAxis();

float s3eHidControllerGetStick2YAxis();

float s3eHidControllerGetLeftTrigger();

float s3eHidControllerGetRightTrigger();

bool s3eHidControllerGetButtonX();

bool s3eHidControllerGetButtonY();

bool s3eHidControllerGetButtonA();

bool s3eHidControllerGetButtonB();

bool s3eHidControllerGetButtonDPadLeft();

bool s3eHidControllerGetButtonDPadRight();

bool s3eHidControllerGetButtonDPadUp();

bool s3eHidControllerGetButtonDPadDown();

bool s3eHidControllerGetButtonLShoulderDown();

bool s3eHidControllerGetButtonRShoulderDown();

bool s3eHidControllerGetButtonStart();

bool s3eHidControllerGetButtonSelect();

S3E_END_C_DECL

#endif /* !S3E_EXT_HIDCONTROLLER_H */
