/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "GamePad_autodefs.h"
#include "s3eEdk.h"
#include "GamePad.h"
//Declarations of Init and Term functions
extern s3eResult GamePadInit();
extern void GamePadTerminate();


void GamePadRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[20];
    funcPtrs[0] = (void*)GamePad_IsConnected;
    funcPtrs[1] = (void*)GamePad_Update;
    funcPtrs[2] = (void*)GamePad_GetStick1XAxis;
    funcPtrs[3] = (void*)GamePad_GetStick1YAxis;
    funcPtrs[4] = (void*)GamePad_GetStick2XAxis;
    funcPtrs[5] = (void*)GamePad_GetStick2YAxis;
    funcPtrs[6] = (void*)GamePad_GetLeftTrigger;
    funcPtrs[7] = (void*)GamePad_GetRightTrigger;
    funcPtrs[8] = (void*)GamePad_GetButtonX;
    funcPtrs[9] = (void*)GamePad_GetButtonY;
    funcPtrs[10] = (void*)GamePad_GetButtonA;
    funcPtrs[11] = (void*)GamePad_GetButtonB;
    funcPtrs[12] = (void*)GamePad_GetButtonDPadLeft;
    funcPtrs[13] = (void*)GamePad_GetButtonDPadRight;
    funcPtrs[14] = (void*)GamePad_GetButtonDPadUp;
    funcPtrs[15] = (void*)GamePad_GetButtonDPadDown;
    funcPtrs[16] = (void*)GamePad_GetButtonLShoulderDown;
    funcPtrs[17] = (void*)GamePad_GetButtonRShoulderDown;
    funcPtrs[18] = (void*)GamePad_GetButtonStart;
    funcPtrs[19] = (void*)GamePad_GetButtonSelect;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[20] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("GamePad", funcPtrs, sizeof(funcPtrs), flags, GamePadInit, GamePadTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int GamePadStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&GamePadRegisterExt;
    return 0;
}

int g_GamePadVal = GamePadStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    GamePadRegisterExt();
}
#endif

#endif
